- repo: local
  hooks:
    - id: ai-commit-message
      name: AI Commit Message Generator
      entry: python main.py  # Path to your script that generates commit messages
      language: python  # The language for the script
      files: \.(py)$  # Apply to Python files
      pass_filenames: false  # No need to pass filenames to the script; it's based on the diff
