repos:
-   repo: local
    hooks:
    -   id: generate-commit-message
        name: Generate Commit Message
        entry: python main.py  # Ensure the script runs
        language: system
        args: []
        stages: [prepare-commit-msg]
        pass_filenames: true
        always_run: true
        files: ".*"  # Run on all file types
