repos:
-   repo: local
    hooks:
    -   id: ai-commit-generator
        name: Generate AI Commit Message
        entry: python ai-commit-generator/main.py
        language: system
        stages: [prepare-commit-msg]
        pass_filenames: true
        always_run: true
